# Use root/mysql as user/password credentials
version: '3.9'

services:
  mysql:
    image: arm64v8/mariadb:10.2
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./custom_mysql.cnf:/etc/mysql/conf.d/custom_mysql.cnf
      - mysql-volume:/var/lib/mysql
    networks:
      - backend

  wordpress:
    image: arm64v8/wordpress
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      #WORDPRESS_DEBUG: 1
    volumes:
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
      - ./data/${WORDPRESS_WP_CONTENT_DIR}:/var/www/html
    networks:
      - backend
      - frontend

volumes:
  mysql-volume:

networks:
  frontend:
  backend:
