version: '3.9'

services:
  proxy:
    image: "traefik"
    container_name: proxy
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # CUSTOM CERTS
      - "--providers.file.directory=/etc/traefik/dynamic"
      # Lets Encrypt
      # - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      # - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      # - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    #  DEBUG
      # - "--api.debug=true"
      # - "--log.level=DEBUG"
    ports:
      # - "80:80"
      - "443:443"
#      - "8080:8080"
    depends_on:
      - wordpress
    volumes:
      # CUSTOM CERTS
      - ./traefik-certs.yml:/etc/traefik/dynamic/traefik-certs.yml
      - ./data/certs:/etc/certs
      # Lets Encrypt
      #- ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./custom_mysql.cnf:/etc/mysql/conf.d/custom_mysql.cnf
      - mysql-volume:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=1

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_CONFIG_EXTRA: define('WP_REDIS_HOST', 'redis');define('WP_CACHE_KEY_SALT', '${WP_CACHE_KEY_SALT}');
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(${WORDPRESS_URLS})
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.entrypoints=web,websecure
      - traefik.http.middlewares.wordpress.headers.SSLRedirect=true
      - traefik.http.middlewares.wordpress.headers.STSSeconds=315360000
      - traefik.http.middlewares.wordpress.headers.browserXSSFilter=true
      - traefik.http.middlewares.wordpress.headers.contentTypeNosniff=true
      - traefik.http.middlewares.wordpress.headers.forceSTSHeader=true
      - traefik.http.middlewares.wordpress.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.wordpress.headers.STSPreload=true
      # Lets Encrypt
      # - traefik.http.middlewares.wordpress.headers.SSLHost=${DEFAULT_HOST_NAME}
      # - traefik.http.routers.wordpress.tls.certresolver=mytlschallenge
    volumes:
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
      - ./data/${WORDPRESS_CONTENT_DIR}:/var/www/html

volumes:
  mysql-volume:
