version: '3.9'

services:
  proxy:
    image: "traefik"
    container_name: proxy
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # CUSTOM CERTS
      - "--providers.file.directory=/etc/traefik/dynamic"
      # Lets Encrypt
      # - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      # - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      # - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    #  DEBUG
    #  - "--api.debug=true"
    #  - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
#      - "8080:8080"
    depends_on:
      - wordpress
    volumes:
      # CUSTOM CERTS
      - ./traefik-certs.yml:/etc/traefik/dynamic/traefik-certs.yml
      - ./data/certs:/etc/certs
      # Lets Encrypt
      #- ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mysql:
    image: mariadb:10.7.3
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./custom_mysql.cnf:/etc/mysql/conf.d/custom_mysql.cnf
      - mysql-volume:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      #WORDPRESS_DEBUG: 1
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`${WORDPRESS_URL}`)
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.routers.wordpress.entrypoints=web,websecure
      - traefik.http.middlewares.wordpress.headers.SSLRedirect=true
      - traefik.http.middlewares.wordpress.headers.STSSeconds=315360000
      - traefik.http.middlewares.wordpress.headers.browserXSSFilter=true
      - traefik.http.middlewares.wordpress.headers.contentTypeNosniff=true
      - traefik.http.middlewares.wordpress.headers.forceSTSHeader=true
      - traefik.http.middlewares.wordpress.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.wordpress.headers.STSPreload=true
      # Lets Encrypt
      # - traefik.http.middlewares.wordpress.headers.SSLHost=${DEFAULT_HOST_NAME}
      # - traefik.http.routers.wordpress.tls.certresolver=mytlschallenge
    volumes:
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
      - ./data/${WORDPRESS_CONTENT_DIR}:/var/www/html

volumes:
  mysql-volume:
